### PR TITLE
Expose duration to `showSimpleNotification`

### PR DESCRIPTION
**Pull request by elvisun**
Hi there, thanks a lot for making this plugin available! 

Noticed the `duration` param was missing, is it cool if we add it in?

### CODE REVIEW

**Comment by boyan01** [comment]
Logic looks good to me, but the code seems has a wrong indention format. 

could you reformat the code ?

**Comment by elvisun** [comment]
sg I ran dartfmt over this file, although my setting might have been different from what you used for this project. ptal, thanks!

**Comment by boyan01** [comment]
ohhh, i got it... I modified the maximum line length to 120 in the settings.

alright, maybe I should take a look for dart's lint to avoid this kind of situation from happening again

**Comment by elvisun** [comment]
Awesome thanks so much for merging, let me know when you have a chance to do another release of this plugin!! 

linting wise we use [80](https://dart.dev/guides/language/effective-dart/style#avoid-lines-longer-than-80-characters) for all languages at google (except Java is 100 😂), but I've also noticed some flutter code do get ugly if they get squished.

**Comment by boyan01** [comment]
> when you have a chance to do another release of this plugin

1.0.5 has been released. ptal: https://pub.dev/packages/overlay_support/versions

>  I've also noticed some flutter code do get ugly if they get squished.

I think so.  And [flutter seems also do not use the 80 to dart' line length](https://github.com/flutter/flutter/blob/54c9441723ec61baaeb0fbf71fdcf4e415116e6e/analysis_options.yaml#L117).

**Pull request merged**
